name: fiurozz

services:
  project-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVER_PORT: 8086
      DATABASE_URL: ${DATABASE_URL}
      SPRING_DATA_REDIS_HOST: redis
    ports:
      - "${PROJECT_SERVICE_PORT:-8086}:8086"
    depends_on:
      redis:
        condition: service_healthy
