name: fiurozz

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    ports:
      - "${USER_SERVICE_PORT:-8082}:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started
